name: Check the quality of my code
on:
  push:
    paths:
      - '**/*.dart' # Run when any Dart file is modified
      - '**/pubspec.yaml' # Run when pubspec.yaml is modified
      - '**/lib/**' # Run when files in the lib directory are modified

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis
        run: flutter analyze
